### PR TITLE
Updates int and float alias to work with numpy version 1.24.2

### PR DESCRIPTION
**Pull request by joshia5**
Thanks and regards,
Aditya Joshi

### CODE REVIEW

**Comment by sshiraiwa** [comment]
Thank you. This PR may take a while to merge. At the moment, 

Numba requires numpy <1.24
Matplotlib 3.7.1 requres numpy >= 1.24

For now, the safe option is to muse matplotlib 3.6.x for now and numpy <=1.23.

**Comment by sshiraiwa** [comment]
HI @joshia5 
I tend to think we should be explicit at the size of variable when it has to be so. Also, we should change all np.float and np.int, not picking a couple of them.

**Comment by joshia5** [comment]
@sshiraiwa all right. does int-> int32 and float->float64 makes sense for these variables?

**Comment by sshiraiwa** [comment]
Yes. Thank you

**Comment by joshia5** [comment]
@sshiraiwa i think that should be all of them

**Pull request merged**
